### ISSUE TITLE
Adjust versioning scheme

### ISSUE THREAD

**Issue by MoisesGSalas** [eduNEXT/codejailservice#22]
This web service is tied to the [`tutor-contrib-codejail`](https://github.com/eduNEXT/tutor-contrib-codejail) and at the moment it follows the tutor versioning scheme (each major version reflects an openedx release, starting with 10->Juniper).

The main problem is that each tag in the tutor plugins must hava a mirror in the codejailservice repository, because that's [how code for the image is retrieved](https://github.com/eduNEXT/tutor-contrib-codejail/blob/b30a150f368a675a420b3b08207186028086e258/tutorcodejail/templates/codejail/build/codejail/Dockerfile#L31C71-L31C93).

I propose instead that we use something more akin to the way tutor plugins and IDAs map. IDAs (like [edx_notes_api](https://github.com/openedx/edx-notes-api), [cs_comments_service](https://github.com/openedx/cs_comments_service/)) use the `open-release/<release-name>.<tag-number>` for versioning and their plugins keep an additional [variable that points to the open-release tag](https://github.com/overhangio/tutor-notes/blob/master/tutornotes/plugin.py#L25) while retaining the tutor versioning system. 

I think the redwood upgrade is a good opportunity for this. We can probably start using release/redwood.1 taking into account the renaming of release branches for sumac (see: [Should we rename the release branches?](https://discuss.openedx.org/t/should-we-rename-the-release-branches/8827))

**Comment by MaferMazu** [comment]
Thank you for this proposal, @MoisesGSalas. I have experienced issues with this plugin mirror versioning before, and your proposal sounds good. I agree with this proposal and using release/.

This solves https://github.com/eduNEXT/tutor-contrib-codejail/issues/51

**Comment by MoisesGSalas** [comment]
I went ahead an tagged the latest commit with the `release/redwood.1` tag. I also created a branch redwood to somewhat mimic the same process as other openedx IDAs.

I also released the v18.0.0 of tutor-contrib-codejail.
